### ISSUE TITLE
[Minor] Unicode zero-width space breaking some links

### ISSUE THREAD

**Issue by chvancooten** [subat0mik/Misconfiguration-Manager#22]
Hi! First of all, congratulations on this awesome project, it's an amazing reference already.

I noticed a (very minor) issue with some Unicode characters breaking links from some of the Markdown technique descriptions. Specifically, there are some Zero-Width spaces (`\u200b`) floating around after hyperlinks, which actually break the link as follows (example from [CRED-1](https://github.com/subat0mik/Misconfiguration-Manager/blob/0afd6b2bde80a40d3fd8b365301345cfc3b442e2/attack-techniques/CRED/CRED-1/cred-1_description.md)):

``` 
https://github.com/MWR-CyberSec/PXEThief%E2%80%8B
```

Here's the full list (obviously, not all of these are actually breaking links):
![image](https://github.com/subat0mik/Misconfiguration-Manager/assets/25614522/9a9a76c7-c87d-4c9c-a27f-25c88795f916)

It's obviously simple  to remediate with a single find-and-replace and I would submit a PR for this, but it's so minor that I wouldn't want to take 'contributor' credit for it 😂. Let me know if that's what you prefer anyway.

**Comment by Mayyhem** [comment]
Thanks @chvancooten ! I just pushed these changes. We appreciate the report!
